services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lab10_django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    environment:
      ALLOWED_HOSTS: "*"
      DB_NAME: hotel_db
      DB_USER: hotel_user
      DB_PASSWORD: hotel_pass
      DB_HOST: maslyhan_db
      DB_PORT: 5432
    networks:
      - lab9_network

networks:
  lab9_network:
    external: true
